services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: twitch-alerts-bot
    restart: unless-stopped
    volumes:
      - ./app/data:/app/data
    environment:
      - TZ=Europe/Moscow
    env_file:
      - ./app/.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
